# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Face ID for Intercom
version: "1.3.7"
slug: faceid_intercom
description: FaceId for Intercom
url: "https://github.com/danieltabrizian/IntercomFaceid/tree/main/intercomfaceid"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
map:
  - share:rw
options:
  message: "Hello world..."
schema:
  message: "str?"
build:
  dockerfile: Dockerfile
  args:
    - BUILD_FROM=docker.io/danieltabrizian/intercomfaceid:latest"
