# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: IntercomFaceId
version: "1.0.1"
slug: intercomfaceid
description: Faceid softrware for intercoms
url: "https://github.com/danieltabrizian/IntercomFaceid/tree/main/intercomfaceid"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
map:
  - share:rw
options:
  message: "Hello world..."
schema:
  message: "str?"
image: "docker.io/danieltabrizian/intercomfaceid:latest"
