name: Face ID for Intercom
version: "1.7.6"
slug: faceid_intercom
description: FaceId for Intercom
url: "https://github.com/danieltabrizian/IntercomFaceid/tree/main/intercomfaceid"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
map:
  - config:rw  # Access to the Home Assistant config folder
  - share:rw   # Access to the Home Assistant share folder
hassio_api: true
memory: "4096M"
devices:
  - /dev/ttyUSB0:/dev/ttyUSB0  # USB device for intercom
  - /dev/video0:/dev/video0    # Video device, likely a camera
options:
  usb_port: "/dev/ttyUSB0"
  baudrate: 9600
schema:
  usb_port: str
 ​⬤