# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Face ID for Intercom
version: "1.8.2"
slug: faceid_intercom
description: FaceId for Intercom
url: "https://github.com/danieltabrizian/IntercomFaceid/tree/main/intercomfaceid"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
map:
  - config:rw
hassio_api: true
memory: "4096M"
devices:
  - /dev/ttyUSB0:/dev/ttyUSB0
  - /dev/video0:/dev/video0
options:
  usb_port: "/dev/ttyUSB0"
  baudrate: 9600
schema:
  usb_port: str
  baudrate: int
build:
  dockerfile: Dockerfile
  args:
    - BUILD_FROM=docker.io/danieltabrizian/intercomfaceid:latest"
