name: IntercomFaceId
version: "1.0.0"
slug: intercomfaceid
description: Face recognition for intercom
url: "https://github.com/danieltabrizian/IntercomFaceid"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
map:
  - share:rw
schema:
  message: "str?"
image: "docker.io/danieltabrizian/intercomfaceid:latest"
ports:
  5000/tcp: 5000
startup: "services"
boot: "auto"
